<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<link rel="icon" type="image/ico" href="<?php echo Url::display ('/favicon.ico'); ?>" />
		<?php echo self::headTitle(); ?>
		<?php echo self::headStyle(); ?>
		<?php echo self::headScript(); ?>
	</head>
	<body>

<div id="global">
	<?php $this->partial ('sideMenu'); ?>
	
	<div id="main">
		<?php $this->render (); ?>
	</div>
</div>

	</body>
</html>
