<ul>
	<li <?php if (Request::actionName () == 'activities') { echo 'class="active"'; } ?>>
		<a href="<?php echo Url::display (array ('a' => 'activities')); ?>">Activités en cours</a>
	</li>
	<li <?php if (Request::actionName () == 'inbox') { echo 'class="active"'; } ?>>
		<a href="<?php echo Url::display (array ('a' => 'inbox')); ?>">Ranger la boîte de réception</a>
	</li>
	<li <?php if (Request::actionName () == 'configuration') { echo 'class="active"'; } ?>>
		<a href="<?php echo Url::display (array ('a' => 'configuration')); ?>">Paramétrer</a>
	</li>
</ul>
