<div class="table">
	<ul class="aside">
		<li class="active"><a href=""><?php echo Translate::t ('manage contexts'); ?></a></li>
	</ul>

	<div class="content_table">
		<form method="post" action="">
			<h2><?php echo Translate::t ('manage contexts'); ?></h2>
			
			<?php foreach ($this->contexts as $context) { ?>
			<label for="context_<?php echo $context->id (); ?>">
				<span><a class="delete" href="<?php echo Url::display (array ('c' => 'context', 'a' => 'delete', 'params' => array ('id' => $context->id ())));?>">X</a></span>
				<?php echo Translate::t ('context number'); ?> <?php echo $context->id () + 1; ?>
			</label>
			<input type="text" name="contexts[]" id="context_<?php echo $context->id (); ?>" value="<?php echo $context->libelle (); ?>" />
			<?php } ?>
			
			<label for="newContext"><?php echo Translate::t ('add context'); ?></label>
			<input type="text" name="newContext" id="newContext" placeholder="<?php echo Translate::t ('new context'); ?>" />
			
			<label> </label>
			<input type="submit" value="<?php echo Translate::t ('validate'); ?>" />
		</form>
	</div>
</div>
