<div id="panel">
	<?php if (!empty ($this->tasks)) { ?>
	<div id="listTasks">
		<ul>
			<?php 
				$tasks = array_reverse ($this->tasks);
				$first = true;
			?>
			<?php foreach ($tasks as $task) { ?>
			<li <?php if ($first) { $first = false; echo 'class="disable"'; } ?>>
				<span><?php echo $task->libelle (); ?></span>
			</li>
			<?php } ?>
		</ul>
	</div>
	
	<?php $task = $tasks[0]; ?>
	<div id="manageTask">
		<h2><?php echo $task->libelle (); ?></h2>
		<form method="post" action="<?php echo Url::display (array ('c' => 'task', 'a' => 'validate')); ?>">
			<label for="date">Date</label>
			<input type="date" name="date" id="date" placeholder="Annee-Mois-Jour" />
			
			<label for="reference">Référencer</label>
			<select name="reference" id="reference">
				<option value="event">Évènement</option>
				<option value="reminder">Rappel</option>
				<option value="action">Action</option>
			</select>
			
			<label for="context">Contexte</label>
			<select class="multi" name="context[]" id="context" multiple="multiple">
				<?php foreach ($this->contexts as $context) { ?>
				<option value="<?php echo $context->id (); ?>"><?php echo $context->libelle (); ?></option>
				<?php } ?>
			</select>
			
			<label for="notes">Notes</label>
			<textarea name="notes" id="notes" placeholder="Ajouter des notes"></textarea>
			
			<input type="hidden" name="id" value="<?php echo $task->id (); ?>" />
			
			<a class="button delete" href="<?php echo Url::display (array ('c' => 'task', 'a' => 'delete', 'params' => array ('id' => $task->id (), 'type' => 'inbox'))); ?>">Supprimer</a>
			<input type="submit" value="Valider" />
		</form>
	</div>
	<?php } else { ?>
	<div class="nothing">Il n'y a pas de tâches dans la boîte de réception.</div>
	<?php } ?>
</div>
