<div id="panel">
	<?php if (!empty ($this->tasks)) { ?>
	<div id="listTasks">
		<ul>
			<?php $tasks = array_reverse ($this->tasks); ?>
			<?php foreach ($tasks as $task) { ?>
			<li class="disable">
				<span><?php echo $task->libelle (); ?></span>
			</li>
			<?php } ?>
		</ul>
	</div>
	
	<?php $task = $tasks[0]; ?>
	<div id="manageTask">
		<h2><?php echo $task->libelle (); ?></h2>
		<form method="post" action="<?php echo Url::display (array ('c' => 'task', 'a' => 'validate')); ?>">
			<label for="date"><?php echo Translate::t ('date'); ?></label>
			<input type="date" name="date" id="date" placeholder="<?php echo Translate::t ('year-month-day'); ?>" />
			
			<label for="reference"><?php echo Translate::t ('reference'); ?></label>
			<select name="reference" id="reference">
				<option value="event"><?php echo Translate::t ('event'); ?></option>
				<option value="reminder"><?php echo Translate::t ('reminder'); ?></option>
				<option value="action"><?php echo Translate::t ('action'); ?></option>
			</select>
			
			<label for="context"><?php echo Translate::t ('context'); ?></label>
			<select class="multi" name="context[]" id="context" multiple="multiple">
				<?php foreach ($this->contexts as $context) { ?>
				<option value="<?php echo $context->id (); ?>"><?php echo $context->libelle (); ?></option>
				<?php } ?>
			</select>
			
			<label for="notes"><?php echo Translate::t ('notes'); ?></label>
			<textarea name="notes" id="notes" placeholder="<?php echo Translate::t ('add notes'); ?>"></textarea>
			
			<input type="hidden" name="id" value="<?php echo $task->id (); ?>" />
			
			<a class="button delete" href="<?php echo Url::display (array ('c' => 'task', 'a' => 'delete', 'params' => array ('id' => $task->id (), 'type' => 'inbox'))); ?>"><?php echo Translate::t ('delete'); ?></a>
			<input type="submit" value="<?php echo Translate::t ('validate'); ?>" />
		</form>
	</div>
	<?php } else { ?>
	<div class="nothing"><?php echo Translate::t ('no activities in inbox'); ?></div>
	<?php } ?>
</div>
