<div id="panel">
	<?php if (!empty ($this->tasks)) { ?>
	<div id="listTasks">
		<div class="line">
			<div class="cell">
			<h2>Activités</h2>
			<ul>
				<?php foreach ($this->tasks as $task) { ?>
				<li class="<?php echo $task->type (); ?>">
					<a href="<?php echo Url::display (array ('c' => 'task', 'a' => 'see', 'params' => array ('id' => $task->id (), 'type' => $task->type (), 'session' => true))); ?>"><?php echo $task->libelle (); ?></a>
				</li>
				<?php } ?>
			</ul>
			
			<?php if (!empty ($this->tasksArchive)) { ?>
			<h2>Archives</h2>
			<ul>
				<?php foreach ($this->tasksArchive as $task) { ?>
				<li class="<?php echo $task->type (); ?> disable">
					<span><?php echo $task->libelle (); ?></span>
				</li>
				<?php } ?>
			</ul>
			
			<script type="text/javascript">
			height = ($('body').height () - 50) / 2;
			$('#listTasks .line .cell ul').height (height);
			</script>
			<?php } else { ?>
			<script type="text/javascript">
			height = ($('body').height () - 50);
			$('#listTasks .line .cell ul').height (height);
			</script>
			<?php } ?>
			</div>
		</div>
	</div>
	<?php } else { ?>
	<div class="nothing">Vous n'avez rien à faire.</div>
	<?php } ?>
</div>
