<div id="panel">
	<?php if (!empty ($this->tasks) || !empty ($this->tasksArchive)) { ?>
	<div id="listTasks">
		<div class="line">
			<div class="cell">
			<?php if (!empty ($this->tasks)) { ?>
			<h2><?php echo Translate::t ('activities'); ?></h2>
			<ul>
				<?php foreach ($this->tasks as $task) { ?>
				<?php 
					$class = $task->type ();
					if ($task->date (true) != 0
					 && $task->date (true) < $this->today) {
						$class .= ' delay';
					}
					if ($task->date (true) >= $this->today
					 && $task->date (true) < $this->today + 86400) {
						$class .= ' today';
					}
				?>
				<li class="<?php echo $class; ?>">
					<a href="<?php echo Url::display (array ('c' => 'task', 'a' => 'change', 'params' => array ('id' => $task->id (), 'type' => $task->type (), 'session' => true))); ?>">
						<?php if ($task->date (true) > 0) { ?>
						<span class="date">(<?php echo $task->date (); ?>)</span>
						<?php } ?>
						<?php echo $task->libelle (); ?>
					</a>
				</li>
				<?php } ?>
			</ul>
			<?php } ?>
			
			<?php if (!empty ($this->tasksArchive)) { ?>
			<h2><?php echo Translate::t ('archives'); ?></h2>
			<ul>
				<?php foreach ($this->tasksArchive as $task) { ?>
				<li class="<?php echo $task->type (); ?> disable">
					<span>
						<?php if ($task->dateFin (true) > 0) { ?>
						<span class="date">(<?php echo Translate::t ('the end'); ?> <?php echo $task->dateFin (); ?>)</span>
						<?php } ?>
						<?php echo $task->libelle (); ?>
						<a class="delete" href="<?php echo Url::display (array ('c' => 'archive', 'a' => 'delete', 'params' => array ('id' => $task->id (), 'type' => $task->type ()))); ?>">&nbsp;</a>
					</span>
				</li>
				<?php } ?>
			</ul>
			<?php } ?>
			
			<script type="text/javascript">
			<?php if (!empty ($this->tasks) && !empty ($this->tasksArchive)) { ?>
			height = ($('body').height () - 100) / 2;
			<?php } else { ?>
			height = ($('body').height () - 50);
			<?php } ?>
			
			$('#listTasks .line .cell ul').height (height);
			</script>
			</div>
		</div>
	</div>
	<?php } else { ?>
	<div class="nothing"><?php echo Translate::t ('nothing to do'); ?></div>
	<?php } ?>
</div>
